
NOMBRE_JUEGO = "Adventure P-Ychigo"

VERDE = (255, 0, 0)
ROJO = (0, 255, 0)
NEGRO = (0, 0, 0)

# Dimensiones de la pantalla
ANCHO_PANTALLA = 1000
ALTO_PANTALLA = 600


# Velocidad del juego
FPS = 20
FPS_MENU = 15


# Rutas de recursos:

ICONO_JUEGO = "imagenes/icono.png"
FONDO_JUEGO_MENU = "imagenes/background_menu.png"
FONDO_JUEGO_LVL1 = "imagenes/background_lvl_1.png"
MUSICA_LVL1 = "sonidos/sonido_pelea.mp3"
SONIDO_MENU = "sonidos/Sonido_Menu.mp3"
SONIDO_MENU_2 = "sonidos/Sonido_Menu_2.mp3"


# Configuracion Pantalla 1:
Y_TEXTO_PUNTOS = 20
X_TEXTO_PUNTOS = 430
Y_TEXTO_VIDA = 20
X_TEXTO_VIDA = 50
LVL1_MAX_Y = 360
LVL1_MIN_Y = 450


# Configuración del personaje:
VIDA_INICIAL = 100
CENTRO_X_CUADRADO = 40
CENTRO_Y_CUADRADO = 30
ANCHO_PERSONAJE = 30
ALTURA_PERSONAJE = 100
POSICION_INICIAL_X = 50
POSICION_INICIAL_Y = 450
VELOCIDAD_PERSONAJE = 12
ALTURA_SALTO = 12
ANCHO_MOVIMIENTO_MAX = 150


#Configuracion Enemigo1:

VIDA_ENEMIGO1 = 10
CENTRO_X_CUADRADO_E1 = 40
CENTRO_Y_CUADRADO_E1 = 30
ANCHO_ENEMIGO1 = 30
ALTURA_ENEMIGO1 = 100
POSICION_INICIAL_X_ENEMIGO1 = 1200
POSICION_INICIAL_Y_ENEMIGO1 = 420
VELOCIDAD_ENEMIGO1 = 10


#Configuracion Enemigo2:

VIDA_ENEMIGO2 = 15
CENTRO_X_CUADRADO_E2 = 70
CENTRO_Y_CUADRADO_E2 = 80
ANCHO_ENEMIGO2 = 50
ALTURA_ENEMIGO2 = 150
POSICION_INICIAL_X_ENEMIGO2 = 1200
POSICION_INICIAL_Y_ENEMIGO2 = 420
VELOCIDAD_ENEMIGO2 = 10