
NOMBRE_JUEGO = "Adventure P-Ychigo"

ROJO = (255, 0, 0)
VERDE = (0, 255, 0)
NEGRO = (0, 0, 0)
AMARILLO = (255, 255, 0)
BLANCO = (255, 255, 255)

# Dimensiones de la pantalla
ANCHO_PANTALLA = 1000
ALTO_PANTALLA = 600


# Velocidad del juego
FPS = 20
FPS_MENU = 15


# Rutas de recursos:

ICONO_JUEGO = "imagenes/icono.png"
FONDO_JUEGO_MENU = "imagenes/background_menu.png"
FONDO_JUEGO_LVL1 = "imagenes/background_lvl_1.png"
MUSICA_LVL1 = "sonidos/sonido_pelea.mp3"
SONIDO_MENU = "sonidos/Sonido_Menu.mp3"
SONIDO_MENU_2 = "sonidos/Sonido_Menu_2.mp3"
SONIDO_SALTO_PJ = "sonidos/Sonido_Salto.mp3"
SONIDO_DANIO = "sonidos/sonido_danio.mp3"
SONIDO_ATAQUE = "sonidos/sonido_ataque.mp3"
SONIDO_MUERTE_E = "sonidos/sonido_muerte.mp3"
SONIDO_RECIBIR_DAÑO_E = "sonidos/sonido_recibir.mp3"

# Configuracion Pantalla 1:
Y_TEXTO_PUNTOS = 20
X_TEXTO_PUNTOS = 430
Y_TEXTO_VIDA = 20
X_TEXTO_VIDA = 50
LVL1_MAX_Y = 360
LVL1_MIN_Y = 450
PUNTOS_GANAR_LVL1 = 300

# Configuración del personaje:
VIDA_INICIAL = 100
CENTRO_X_CUADRADO = 40
CENTRO_Y_CUADRADO = 30
ANCHO_PERSONAJE = 45
ALTURA_PERSONAJE = 110
POSICION_INICIAL_X = 50
POSICION_INICIAL_Y = 450
VELOCIDAD_PERSONAJE = 12
ALTURA_SALTO = 12
ANCHO_MOVIMIENTO_MAX = 150


#Configuracion Enemigo1:

VIDA_ENEMIGO1 = 10
CENTRO_X_CUADRADO_E1 = 100
CENTRO_Y_CUADRADO_E1 = 40
ANCHO_ENEMIGO1 = 30
ALTURA_ENEMIGO1 = 100
POSICION_INICIAL_X_ENEMIGO1 = 1200
POSICION_INICIAL_Y_ENEMIGO1 = 340
VELOCIDAD_ENEMIGO1 = 1
OFFSET_X_RECT_ATAQUE_E1 = 10
OFFSET_Y_RECT_ATAQUE_E1 = 40
ANCHO_RECT_ATAQUE_E1 = 110
ALTO_RECT_ATAQUE_E1 = 30



#Configuracion Enemigo2:

VIDA_ENEMIGO2 = 15
CENTRO_X_CUADRADO_E2 = 100
CENTRO_Y_CUADRADO_E2 = 40
ANCHO_ENEMIGO2 = 60
ALTURA_ENEMIGO2 = 130
POSICION_INICIAL_X_ENEMIGO2 = 1200
POSICION_INICIAL_Y_ENEMIGO2 = 340
VELOCIDAD_ENEMIGO2 = 1
OFFSET_X_RECT_ATAQUE_E2 = -20
OFFSET_Y_RECT_ATAQUE_E2 = 60
ANCHO_RECT_ATAQUE_E2 = 80
ALTO_RECT_ATAQUE_E2 = 100

#Configuracion Enemigo3:

VIDA_ENEMIGO3 = 5
CENTRO_X_CUADRADO_E3 = 70
CENTRO_Y_CUADRADO_E3 = 70
ANCHO_ENEMIGO3 = 70
ALTURA_ENEMIGO3 = 90
POSICION_INICIAL_X_ENEMIGO3 = 1200
POSICION_INICIAL_Y_ENEMIGO3 = 50
VELOCIDAD_ENEMIGO3 = 1
OFFSET_X_RECT_ATAQUE_E3 = -15
OFFSET_Y_RECT_ATAQUE_E3 = 15
ANCHO_RECT_ATAQUE_E3 = 60
ALTO_RECT_ATAQUE_E3 = 80